[server]
headless = true
port = 8501

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#0072B2"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F6FF"
textColor = "#222222"
font = "sans serif"
